version: "3.8"

services:
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony_docker
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4307:3306'
    php:
        build:
            context: ./docker
        volumes:
            - .:/var/www/website
        depends_on:
            - database
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8081:80'
        volumes:
            - .:/var/www/website
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
    node:
        image: node
        working_dir: /var/www
        volumes:
            - ./:/var/www
    mailer:
        image: mailhog/mailhog
        ports:
            - '8026:8025'
